kind: Service
apiVersion: v1
metadata:
  name: app-loadbalancer-https
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "f437f5a9-608f-4d9b-af67-4a9e5d221afd"
spec:
  type: LoadBalancer
  selector:
    app: mydoiinfo-app
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
