kind: Service
apiVersion: v1
metadata:
  name: app-loadbalancer-https
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "2772eba6-b984-4069-94fb-863cfbc2f190"
spec:
  type: LoadBalancer
  selector:
    app: mydoiinfo-app
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
